/* Display buffer pool hit ratios (data, index and XML) */ 

SELECT 
  SUBSTR(BP_NAME,1,20) as BP_NAME, 
  TOTAL_HIT_RATIO_PERCENT as ALL_HR,
  DATA_HIT_RATIO_PERCENT as DATA_HR, 
  INDEX_HIT_RATIO_PERCENT as INX_HR, 
  XDA_HIT_RATIO_PERCENT as XML_HR
FROM 
  SYSIBMADM.BP_HITRATIO;
