/* Show the sort time, and wait time for all sorts by connection */

SELECT
    APPLICATION_HANDLE AS APP_HDL, 
    SUBSTR(CLIENT_USERID,1,10) AS USERID, 
    TOTAL_SECTION_SORTS AS NUM_SORTS, 
    TOTAL_SECTION_SORT_TIME AS TOTAL_TIME, 
    TOTAL_SECTION_SORT_PROC_TIME AS SORT_TIME, 
    TOTAL_SECTION_SORT_TIME - TOTAL_SECTION_SORT_PROC_TIME AS WAIT_TIME
FROM 
    TABLE(MON_GET_CONNECTION(NULL,-1))
