SELECT 
  ELAPSED_TIME_MIN, 
  SUBSTR(AUTHID,1,10) AS AUTH_ID,
  AGENT_ID,
  APPL_STATUS, 
  SUBSTR(STMT_TEXT,1,20) AS SQL_TEXT
FROM 
  SYSIBMADM.LONG_RUNNING_SQL 
WHERE ELAPSED_TIME_MIN > 0
ORDER BY ELAPSED_TIME_MIN DESC
