/* Show the most active tables */

SELECT
   SUBSTR(TABSCHEMA,1,10) AS SCHEMA, 
   SUBSTR(TABNAME,1,20) AS NAME, TABLE_SCANS,
   ROWS_READ,
   ROWS_INSERTED,
   ROWS_DELETED
FROM 
   TABLE(MON_GET_TABLE('','',-1)) 
ORDER BY ROWS_READ DESC
FETCH FIRST 5 ROWS ONLY
